"""add avatar_hash

Revision ID: 5cf8a08fd8ba
Revises: 759cab41cc87
Create Date: 2016-06-20 12:44:41.351311

"""

# revision identifiers, used by Alembic.
revision = '5cf8a08fd8ba'
down_revision = '759cab41cc87'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
