"""alter posts, add column.

Revision ID: f366f2139157
Revises: 252d05801b3d
Create Date: 2016-06-26 15:39:15.590862

"""

# revision identifiers, used by Alembic.
revision = 'f366f2139157'
down_revision = '252d05801b3d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
