"""reg username

Revision ID: fc36e61ae1b4
Revises: 5dcbe45e6691
Create Date: 2016-06-08 16:01:14.557530

"""

# revision identifiers, used by Alembic.
revision = 'fc36e61ae1b4'
down_revision = '5dcbe45e6691'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
